# Generated by Django 5.0.7 on 2024-09-07 05:24

import crime.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('last_logged_in', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('caseid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('caseno', models.IntegerField()),
                ('case_date', models.DateField()),
                ('nature_of_case', models.CharField(max_length=255)),
                ('case_description', models.TextField(blank=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('recorded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('casestatus', models.CharField(default='ongoing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfCase',
            fields=[
                ('nature_of_case', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('case_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to=crime.models.officer_image_path)),
                ('joined_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_reports/')),
                ('username', models.CharField(max_length=255)),
                ('file_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('NIN_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Contact_no', models.CharField(max_length=20)),
                ('Password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=crime.models.case_image_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crime.casereport')),
            ],
        ),
        migrations.CreateModel(
            name='AdminPosted',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.casereport')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('activity', models.CharField(max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='crime.casereport')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=crime.models.evidence_image_path)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='crime.casereport')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_date', models.DateField()),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crime.officerrecord')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerAndCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('enrollment', models.CharField(max_length=255)),
                ('case_assigned_on', models.DateField(blank=True, null=True)),
                ('case_left_on', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.casereport')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.officerrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PublicResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.adminposted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_message', models.TextField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=crime.models.public_report_attachment_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('statement', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=crime.models.suspect_image_path)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='crime.casereport')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('statement', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=crime.models.victim_image_path)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='crime.casereport')),
            ],
        ),
    ]
